version: '3'

services:
  php:
    build: ./docker/php
    volumes:
      - ./laravel_project:/var/www
      - ./docker/php/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - php-socket:/var/run/php-fpm/
      - db-socket:/var/run/mysqld

  nginx:
    build: ./docker/nginx
    ports:
      - 28000:80
      - 28443:443
    volumes:
      # - ./laravel_project:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - php-socket:/var/run/php-fpm/
    depends_on:
      - php

  db:
    image: mysql:8.0
    env_file:
      - ./docker/db/db.env
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - db-socket:/var/run/mysqld
      - ./docker/db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/db/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      # - ./docker/db/docker.cnf:/etc/mysql/conf.d/docker.cnf
    # ports:
      # - 3306:3306

volumes:
  db-data:
  php-socket:
  db-socket:
